### ISSUE TITLE
Frontend: Add search result address when viewing search results

### ISSUE THREAD

**Issue by laredotornado** [chicommons/maps#75]
When search results are returned from here,

https://prod.chicommons.coop/search

only the name appears, e.g.

Bowmanville Community Garden

We would like to include the address (only the first if there are multiple) beneath the name (in a slightly smaller font), so the result would appear as

Bowmanville Community Garden
5412 N. Bowmanville, Chicago, IL 60625

The JSON object for each search result will resemble the following

```
{
  "id": 3,
  "addresses": [
    {
      "id": 3,
      "street_number": "1842",
      "route": "St",
      "raw": "1842 S Troy St",
      "formatted": "1842 S Troy St",
      "latitude": 41.85595552,
      "longitude": -87.70425024,
      "locality": {
        "id": 63,
        "name": "Chicago",
        "postal_code": "60623",
        "state": {
          "id": 19313,
          "code": "IL",
          "name": "Illinois",
          "country": {
            "id": 484,
            "name": "United States",
            "code": "US"
          }
        }
      }
    }
  ],
  "name": "1800 South Troy Block Club Garden",
}
```

**Comment by nick-hou** [comment]
This is a backend issue first - the coop search API currently only returns ID and name: https://prod.chicommons.coop/coops/?state=IL

I'm not experienced with Django, but I added 'addresses' to CoopSearchSerializer's fields and got an array containing only one int - see attached screenshot

![Screenshot 2021-06-14 213038](https://user-images.githubusercontent.com/68621516/121983963-c8399d80-cd57-11eb-915f-f0dc39fcd0bb.jpg)

**Comment by laredotornado** [comment]
Shoot that is a good call, looks like I'll need to do a little backend work
here.  Btw going to send you an invite soon, was trying to get ahold of the
ChiCommons zoom line but we may have to settle for Google meet.

**Comment by laredotornado** [comment]
@nick-hou , please check out the latest -- I pushed some changes so that the search now returns the addresses in the JSON (I forgot the search was using a different serializer than what was used in other forms)

**Comment by nick-hou** [comment]
@laredotornado I'm still not seeing address being populated in the React hook. Your commit from last night only has one change to a test script - did you stage everything?

**Comment by laredotornado** [comment]
Ah, it has been a long week and we're only on Wednesday!  Check the latest,
should be an update to

web/directory/serializers.py .
